// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace PhotoMap.Backend.Entities
{
    public partial class User
    {
        public User()
        {
            Photos = new HashSet<Photo>();
        }

        [Key]
        public Guid UserRowguid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public DateTime? CreatedAt { get; set; }

        public virtual ICollection<Photo> Photos { get; set; }
    }
}